# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
# Linux
- task: ShellScript@2
  inputs:
    scriptPath: build.sh
  condition: eq( variables['Agent.OS'], 'Linux' ) 
# macOS
- task: ShellScript@2
  inputs:
    scriptPath: build.sh
  condition: eq( variables['Agent.OS'], 'Darwin' )
# Windows
- task: CMake@1
  inputs:
    cmakeArgs: '-G"Visual Studio 16 2019" ..'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
- task: VSBuild@1
  inputs:
    solution: 'build\*.sln'
    msbuildArchitecture: 'x64'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/artifacts'
    includeRootFolder: false

- task: PublishBuildArtifacts@1 